---
- name: Configuración de la VM
  hosts: podman_vm
  become: yes
  become_user: root
  tasks:
    - name: Tarea 1 - Instalar herramientas requeridas
      ansible.builtin.yum:
        name:
          - podman
          - skopeo
          - httpd
          - httpd-tools
          - openssl
        state: present

    - name: Tarea 2 - Instalar módulo passlib
      ansible.builtin.pip:
        name: passlib
        state: present

    - name: Tarea 3 - Crear directorio de trabajo
      ansible.builtin.file:
        path: "/webserver"
        state: directory
        owner: root
        group: root
        mode: "0700"

    - name: Tarea 4 - Crear archivo de credenciales
      community.general.htpasswd:
        path: "/webserver/.cred"
        name: caramelo
        password: mentolin
        owner: root
        group: root
        mode: "0664"

    - name: Tarea 5 - Generar certificado autofirmado
      community.crypto.openssl_privatekey:
        path: "/webserver/localhost.key"
        size: 2048
        owner: root
        group: root
        mode: "0664"

    - name: Tarea 6 - Crear petición de firma del certificado
      community.crypto.openssl_csr:
        path: "/webserver/localhost.csr"
        privatekey_path: "/webserver/localhost.key"
        subject:
          C: ES
          ST: Madrid
          L: Madrid
          O: DevOps
          OU: Ejemplo
          CN: vm1
        owner: root
        group: root
        mode: "0664"

    - name: Tarea 7 - Crear certificado autofirmado
      community.crypto.x509_certificate:
        path: "/webserver/localhost.crt"
        privatekey_path: "/webserver/localhost.key"
        csr_path: "/webserver/localhost.csr"
        provider: selfsigned
        owner: root
        group: root
        mode: "0600"
