---
- name: Configuración del servidor Apache
  hosts: podman_vm
  become: yes
  become_user: root
  tasks:
    - name: Tarea 8 - Crear archivo index.html
      ansible.builtin.template:
        src: templates/index.html
        dest: /webserver/index.html
        owner: root
        group: root
        mode: '0644'
      become: true

    - name: Tarea 9 - Crear archivo httpd.conf
      ansible.builtin.template:
        src: templates/httpd.conf
        dest: /webserver/httpd.conf
        owner: root
        group: root
        mode: '0644'
      become: true

    - name: Tarea 9 - Crear archivo .htaccess
      ansible.builtin.template:
        src: templates/.htaccess
        dest: /webserver/.htaccess
        owner: root
        group: root
        mode: '0644'
      become: true

    - name: Tarea 10 - Crear archivo Containerfile
      ansible.builtin.template:
        src: templates/Containerfile
        dest: /webserver/Containerfile
        owner: root
        group: root
        mode: '0644'
      become: true
