---
- name: Configuración del servidor web con Podman y Ansible
  hosts: podman_vm
  become: no
  tasks:
    - name: Tarea 1 - Instalar herramientas requeridas
      become: yes
      package:
        name:
          - podman
          - skopeo
          - httpd
          - httpd-tools
          - openssl
        state: present

    - name: Tarea 2 - Instalar módulo passlib
      become: yes
      pip:
        name: passlib
        state: present

    - name: Tarea 3 - Crear directorio de trabajo
      file:
        path: webserver
        state: directory

    - name: Tarea 4 - Crear archivo de credenciales
      become: yes
      htpasswd:
        path: webserver/.cred
        name: caramelo
        password: mentolin
        owner: adminuser
        group: adminuser
        mode: '0600'

    - name: Tarea 5 - Generar certificado autofirmado
      openssl_privatekey:
        path: webserver/localhost.key
        size: 2048

    - name: Tarea 6 - Crear petición de firma del certificado
      openssl_csr:
        path: webserver/localhost.csr
        privatekey_path: webserver/localhost.key
        subject:
          C: ES
          ST: Madrid
          L: Madrid
          O: DevOps
          OU: Ejemplo
          CN: vm1

    - name: Tarea 7 - Crear certificado autofirmado
      openssl_certificate:
        path: webserver/localhost.crt
        privatekey_path: webserver/localhost.key
        csr_path: webserver/localhost.csr
        provider: selfsigned

    - name: Tarea 8 - Definir página principal del servidor web
      copy:
        content: "<p>Web Server protegido por X509 y log por usuario y password</p>"
        dest: /home/adminuser/webserver/index.html

    - name: Tarea 9 - Establecer permisos en el archivo index.html
      file:
        path: /home/adminuser/webserver/index.html
        owner: adminuser
        group: adminuser
        mode: "0644"

    - name: Tarea 10 - Definir configuración del servidor web
      copy:
        content: |
          ServerRoot "/usr/local/apache2"
          Listen 443
          # Resto del contenido del archivo httpd.conf
        dest: webserver/httpd.conf

    - name: Tarea 11 - Establecer configuración de autenticación básica
      copy:
        content: |
          AuthType Basic
          AuthName "Restricted Content"
          AuthUserFile /usr/local/apache2/.cred
          Require valid-user
        dest: webserver/.htaccess

    - name: Tarea 12 - Crear el archivo Containerfile
      template:
        src: templates/Containerfile.j2
        dest: /home/adminuser/webserver/Containerfile

    - name: Tarea 13 - Generar imagen del contenedor
      command:
        cmd: sudo podman build -t webserver -f Containerfile .
      args:
        chdir: /home/adminuser/webserver
      become: yes
      become_user: adminuser

    - name: Tarea 14 - Iniciar sesión en el registro de contenedores
      command:
        cmd: podman login maseiraacr.azurecr.io -u maseiraACR -p TLRy0jHXGKgMYQtE5m5DsVQHi5Y9UruO1aF6e8p2WF+ACRBB+dMX

    - name: Tarea 15 - Subir imagen del contenedor al registro
      command:
        cmd: sudo podman push maseiraacr.azurecr.io/webserver:casopractico2
      become: yes
      become_user: adminuser

    - name: Tarea 16 - Crear contenedor del servicio web
      shell: podman run -d --name web -p 8080:443 maseiraacr.azurecr.io/webserver:casopractico2
