 - name: Configuración del servidor web con Podman y Ansible
  hosts: podman_vm
  become: yes
  become_user: root
  tasks:   
    - name: Tarea 8 - Definir página principal del servidor web
      template:
        src: templates/index.html
        dest: "/webserver/index.html"
        owner: adminuser
        group: adminuser
        mode: "0644"

    - name: Tarea 9 - Definir configuración del servidor web
      template:
        src: templates/httpd.conf
        dest: "/webserver/httpd.conf"
        owner: adminuser
        group: adminuser
        mode: "0644"

    - name: Tarea 10 - Definir configuración de autenticación básica
      template:
        src: templates/.htaccess
        dest: "/webserver/.htaccess"
        owner: adminuser
        group: adminuser
        mode: "0644"

    - name: Tarea 11 - Crear el archivo Containerfile
      template:
        src: templates/Containerfile
        dest: "/webserver/Containerfile"
        owner: adminuser
        group: adminuser
        mode: "0644"