---
- name: Crear Imagenes y subirlas al registry para AKS
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Descargar imágenes desde el repositorio público de Microsoft
      ansible.builtin.command: >
        docker pull mcr.microsoft.com/oss/bitnami/redis:6.0.8 &&
        docker pull mcr.microsoft.com/azuredocs/azure-vote-front:v1
      become: true

    - name: Etiquetar imágenes descargadas
      ansible.builtin.command: >
        docker tag mcr.microsoft.com/oss/bitnami/redis:6.0.8 {{ registry_acr }}/redis:6.0.8:casopractico2 &&
        docker tag mcr.microsoft.com/azuredocs/azure-vote-front:v1 {{ registry_acr }}/azure-vote-front_v1:casopractico2
      become: true

    - name: Iniciar sesión en el registro de contenedores de Azure
      azure_rm_containerregistry:
        resource_group: cp2_resource_group
        name: {{ registry_acr }}
        state: present
        username: {{ registry_username }}
        password: {{ registry_password }}

    - name: Subir imágenes al registro de contenedores de Azure
      ansible.builtin.command: >
        docker push {{ registry_acr }}/redis:6.0.8-casopractico2 &&
        docker push {{ registry_acr }}/azure-vote-front_v1:casopractico2
      become: true