- name: Adjuntar ACR al AKS
  hosts: localhost
  tasks:
    - name: Tarea 0 - Adjuntar ACR al AKS
      shell: |
        az login --username "{{ lookup('env', 'AZURE_USERNAME') }}" \
          --password "{{ lookup('env', 'AZURE_PASSWORD') }}" \
          --tenant "{{ lookup('env', 'AZURE_TENANT') }}"
        az aks update -n "{{ kubernetes_cluster_name }}" -g "{{ resource_group_name }}" --attach-acr "{{ registry_username }}"
      become: true
