---
- name: Desplegar Grafana en AKS
  hosts: aks_worker
  gather_facts: no
  tasks:

    - name: Tarea 0 - Instalar herramientas requeridas en el worker
      ansible.builtin.yum:
        name:
          - podman
          - kubectl
        state: present
      become: true
      become_user: root

    - name: Tarea 1 - Crear directorio de trabajo en el worker
      ansible.builtin.file:
        path: "/grafana"
        state: directory
        owner: root
        group: root
        mode: "0775"
      become: true
      become_user: root

    - name: Tarea 2 - Obtener las credenciales del cluster AKS
      azure_rm_kubernetescluster_info:
        resource_group: "{{ azurerm_resource_group.acr_rg.name }}"
        name: "aks_cluster_kubernetes"
        client_id: "{{ azure_client_id }}"
        tenant: "{{ azure_tenant_id }}"
      register: cluster_info

    - name: Tarea 3 - Configurar kubectl con las credenciales del cluster AKS
      ansible.builtin.copy:
        content: "{{ cluster_info.kube_config_raw }}"
        dest: ~/.kube/config
        mode: "0600"

    - name: Tarea 4 - Descargar imagen de Grafana y hacer el tag
      ansible.builtin.command:
        cmd: podman pull grafana:latest && podman tag grafana:latest "{{ registry_acr }}/grafana:casopractico2"
      become: true
      become_user: root

    - name: Tarea 5 - Iniciar sesión en el registro de contenedores
      containers.podman.podman_login:
        registry: "{{ registry_acr }}"
        username: "{{ registry_username }}"
        password: "{{ registry_password }}"
      become: true
      become_user: root

    - name: Tarea 6 - Subir imagen del contenedor al registro
      containers.podman.podman_image:
        name: "{{ registry_acr }}/grafana:casopractico2"
        push: true
      become: true
      become_user: root

