- name: Actualizar AKS y adjuntar ACR
  hosts: localhost
  tasks:
    - name: Actualizar AKS y adjuntar ACR
      shell: |
        az login --username "{{ lookup('env', 'AZURE_USERNAME') }}" \
          --password "{{ lookup('env', 'AZURE_PASSWORD') }}" \
          --tenant "{{ lookup('env', 'AZURE_TENANT') }}"
        az aks update -n "{{ kubernetes_cluster_name }}" -g "{{ resource_group_name }}" --attach-acr "{{ registry_username }}"
      become: true
