    - name: Tarea 7 - Desplegar Grafana en AKS
      kubernetes.core.k8s:
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: grafana
            labels:
              app: grafana
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: grafana
            template:
              metadata:
                labels:
                  app: grafana
              spec:
                containers:
                  - name: grafana
                    image: "{{ registry_acr }}/grafana:casopractico2"
                    ports:
                      - containerPort: 3000
                    volumeMounts:
                      - name: grafana-storage
                        mountPath: /var/lib/grafana
                volumes:
                  - name: grafana-storage
                    persistentVolumeClaim:
                      claimName: grafana-pvc

    - name: Tarea 8 - Exponer servicio de Grafana en AKS
      kubernetes.core.k8s:
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            name: grafana-service
          spec:
            type: LoadBalancer
            ports:
              - protocol: TCP
                port: 80
                targetPort: 3000
            selector:
              app: grafana
