---
- name: Configurar y desplegar en AKS
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Crear namespace en el clúster de AKS
      kubernetes.core.k8s:
        kubeconfig: kubeconfig.yaml
        kind: Namespace
        name: azurevote-redis
        state: present

    - name: Aplicar manifiesto YAML en el clúster de AKS
      kubernetes.core.k8s:
        kubeconfig: kubeconfig.yaml
        src: manifest.yml
        namespace: azurevote-redis
        state: present